// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CAjwPnqGPBuVJ1dGjAMT0Gn6aScYC3M',
    appId: '1:1057229849830:web:ecf8c57ba03c6ee899a727',
    messagingSenderId: '1057229849830',
    projectId: 'chat-app-schools',
    authDomain: 'chat-app-schools.firebaseapp.com',
    databaseURL: 'https://chat-app-schools-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-schools.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMd2CIMbagi0XzdQQQ3VgL-w2xhXAqrkw',
    appId: '1:1057229849830:android:2e806072b2e3460099a727',
    messagingSenderId: '1057229849830',
    projectId: 'chat-app-schools',
    databaseURL: 'https://chat-app-schools-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-schools.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMaX4QdZM_MiUouTYn_OthalOyhBYV6fI',
    appId: '1:1057229849830:ios:56f63d540491cedd99a727',
    messagingSenderId: '1057229849830',
    projectId: 'chat-app-schools',
    databaseURL: 'https://chat-app-schools-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-schools.appspot.com',
    iosBundleId: 'com.virtualhelp.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMaX4QdZM_MiUouTYn_OthalOyhBYV6fI',
    appId: '1:1057229849830:ios:434d70a8b49b6ae399a727',
    messagingSenderId: '1057229849830',
    projectId: 'chat-app-schools',
    databaseURL: 'https://chat-app-schools-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-schools.appspot.com',
    iosBundleId: 'com.example.chat.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4CAjwPnqGPBuVJ1dGjAMT0Gn6aScYC3M',
    appId: '1:1057229849830:web:c2ecdedf5a4c3c6399a727',
    messagingSenderId: '1057229849830',
    projectId: 'chat-app-schools',
    authDomain: 'chat-app-schools.firebaseapp.com',
    databaseURL: 'https://chat-app-schools-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-schools.appspot.com',
  );
}
